from .pip_pulidflux import NODE_CLASS_MAPPINGS as PULID_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PULID_DISPLAY_NAME_MAPPINGS

# 已移除pip_pulidflux_pro模块的导入

# 只使用pip_pulidflux的节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(PULID_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(PULID_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
